version: 2
updates:
- package-ecosystem: uv
  allow:
    - dependency-type: all
  commit-message:
    prefix: Bug 2046283 - deps
  cooldown:
    default-days: 7
  directory: "/"
  open-pull-requests-limit: 99
  schedule:
    interval: monthly
- package-ecosystem: "github-actions"
  commit-message:
    prefix: Bug 2046283 - deps
  cooldown:
    default-days: 7
  directory: "/"
  schedule:
    interval: monthly
