[build-system]
requires = ["setuptools>=80", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
]
dependencies= [
  "requests",
  "rs_parsepatch",
  "sentry-sdk>=2.68.0",
  "simple-github >= 3.2.0",
  "taskcluster",
]
description =  "Select reviewers based on a diff and a set of rules"
dynamic = ["version"]
license = "MPL-2.0"
maintainers = [
    {name = "Mozilla Conduit", email = "conduit-team@mozilla.com"},
]
name = "reviewer-selector"
# NOTE: When bumping this, also update docker/Dockerfile to match.
requires-python = ">=3.12"

[dependency-groups]
dev = [
  "pytest",
  "pytest-cov",
  "requests-mock",
  "ruff",
]

[project.scripts]
reviewer-selector = "reviewer_selector:cli"
gh-token-generator = "gh_token_generator:main"

[tool.pytest]
addopts = ["--cov", "--cov-report", "html"]

[tool.ruff.lint]
extend-select = ["I"]
